### ISSUE TITLE
[noob alert] Installation errors

### ISSUE THREAD

**Issue by jkim5959** [vaxerski/Hyprland#13]
I think it wants me to install cairo and pango

I followed wiki and installed all the dependencies but made an error cos it couldnt find cairo and pango

So i installed those then ran sudo make install again

Then it says

cp: cannot create regular file '/usr/share/wayland-sessions/' : Not a directory

So i created /usr/share/wayland-sessions/

Then i ran sudo make install again

Now 
![Screenshot_Hyprland_2022-04-05_12_19_51](https://user-images.githubusercontent.com/85728320/161666484-5bcc0799-9265-48f2-8c8a-bcccaab67861.png)

My /tmp/hypr/hyprland.log is just one line:

[CRITICAL] m_sWLRBackend was NULL!

I installed this on fresh archlinux with qemu/kvm. Nothing apart from Hyprland's dependencies (from the installation wiki) was installed.

I'm pretty sure i made a dumb mistake somewhere cos that's how everything ends up for me. Please forgive my lack of linux skills.

Edit: I did copy config file into .config/hypr/ yet problem persists.

**Comment by vaxerski** [comment]
installing `polkit` should fix the errors. (provided you use systemd)

**Comment by jkim5959** [comment]
I reinstalled it with polkit this time on a new arch. Problem persists unfortunately. I guess it's qemu/kvm issue.

Thanks for replying tho :)
