### ISSUE TITLE
Some games don't work properly

### ISSUE THREAD

**Issue by mifoo** [vaxerski/Hyprland#166]
When I launch some games(Apex Legends, Star Citizen), no window appears. There is however sound and the menus are interactable. Both games are run through Wine. The games work in sway and plasma. All other games I have tried have worked in Hyprland, both native and with Wine/Proton. 
In the attached log I tried starting Apex Legends, switched workspace, then closed Hyprland. 

[hyprlandd.log](https://github.com/vaxerski/Hyprland/files/8843064/hyprlandd.log)

**Comment by mifoo** [comment]
Trying `hyperctl clients` crashes hyprland... 
I have attached coredump and log from hyprland. 


[core.1562.gz](https://github.com/vaxerski/Hyprland/files/8843851/core.1562.gz)
[hyprlandd2.log](https://github.com/vaxerski/Hyprland/files/8843856/hyprlandd2.log)

**Comment by vaxerski** [comment]
your coredump is either corrupted or doesn't come from the latest commit.

Crash should be fixed, try again.

**Comment by mifoo** [comment]
Redid with latest commit. Had to build `hyprctl` manually because it is not built with make debug. 
[hyprlandd.log](https://github.com/vaxerski/Hyprland/files/8843994/hyprlandd.log)
[core.11569.gz](https://github.com/vaxerski/Hyprland/files/8843995/core.11569.gz)

**Comment by vaxerski** [comment]
something is really wrong with that window. Are Apex Legends and Star Citizen the only games that crash? I don't have either.

**Comment by mifoo** [comment]
The games themselves do not crash, only when I try `hyprctl clients`. Will try some other games but they are the only ones that have crashed that I have tried.

**Comment by vaxerski** [comment]
I've tried many games and havent found that issue yet - can you share your config?

**Comment by mifoo** [comment]
Pretty sure it isn't the config, tested with the example one before I made the issue, but here they are anyway in case I'm missing something. 
[config.txt](https://github.com/vaxerski/Hyprland/files/8844108/config.txt)
[garden.txt](https://github.com/vaxerski/Hyprland/files/8844111/garden.txt)

**Comment by vaxerski** [comment]
yeah seems alright, I'd remove those example rules though if I were you:
![image](https://user-images.githubusercontent.com/43317083/172154141-1bc3ed37-7413-41c7-89a8-83b02ad7f373.png)

**Comment by mifoo** [comment]
Removed the examples and tested some more games. While Apex and Star Citizen are the only games that don't start properly trying `hyprctl clients` seems to crash hyprland with all the games I have tested, both native and wine. 

Tested `hyprctl clients` with just steam and a terminal running as well, is this a normal output? Looks kind of weird to me 
[output.txt](https://github.com/vaxerski/Hyprland/files/8844212/output.txt)

**Comment by mifoo** [comment]
If you have steam and want to test, the free and quite small game OpenTTD is one of the ones I have tested that launches fine but crashes hyprland when I try `hyprctl clients`.

**Comment by vaxerski** [comment]
okay, I'll test.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/172162861-2bcf03ac-7ab5-49b8-a4c9-8f726041b1b6.png)

works as expected for me...

**Comment by mifoo** [comment]
Tested again and worked fine. Then tried starting steam and testing and it crashed, try that? No clue how that would impact it though since just steam also worked.

**Comment by vaxerski** [comment]
I used the non-steam version. Will try the steam one.

**Comment by mifoo** [comment]
Tried again with only steam and no games open and it crashed

**Comment by vaxerski** [comment]
oops, fixed. Now it shouldnt crash anymore

**Comment by vaxerski** [comment]
I can't see apex there, only unmanaged X11 windows. also, it abruptly ends at line 609.

If Apex recieves monitor and workspace -1, it's unmanaged. It should never recieve any of those as -1 if it was mapped.

**Comment by mifoo** [comment]
The command itself cuts of in the terminal too. 
Here are the logs if they help any. 
[hyprlandd.log](https://github.com/vaxerski/Hyprland/files/8844731/hyprlandd.log)

**Comment by vaxerski** [comment]
fixed, try now

**Comment by mifoo** [comment]
Line 798 and 799 in the logs seem like a problem, a window is created for Apex then immediately unmapped... 
Will try again

**Comment by mifoo** [comment]
Hyprctl no longer cuts off! Sadly the game still doesn't work though. Isn't showing up in the list either, just kitty and steam.

**Comment by vaxerski** [comment]
then it's unmanaged. Seems like an issue with apex, no? You said youself it unmaps, as you can see in the logs.

**Comment by mifoo** [comment]
Maybe, just weird that it works on sway. Would have thought both would have the problem since hyprland also uses wlroots. Will test some more to see if I can figure anything out.

**Comment by mifoo** [comment]
Managed to get most games to work properly using gamescope. Took a quick peek at sway and they somehow handle the unmanaged windows in a way that makes it work. If that isn't something you're planning to do feel free to close the issue.

**Comment by vaxerski** [comment]
okay, it is a bit different, but I can't really see a reason it'd be wrong. At any rate, since your issue can be fixed with gamescope, I'd close this. I will look into this more in the future.

**Comment by sannagy90** [comment]
I also have the same issue. Gamescope, while works, doesn't support vrr as far as I know. (or I'm doing something wrong). It would be nice if games worked without gamescope. Another game where I experience this is league of legends. The client does show up, but if I move it to another workspace, it's nowhere to be found even though it's in hyprctl clients.
